version: "3.8"

services:
  app:
    build: ./work
    #image: euphony
    restart: always 
    environment:
        MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./work:/usr/src
      # Que no monte archivos en esta ruta
      - /usr/src/node_module
  db:
    image: mongo
    #container_name: 
    restart: always
    ports:
      - "27017"
    container_name: euphony_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
